#!/usr/bin/env python3

"""
AWS CloudWatch Logs の指定のロググループ＆ログストリームにログを出力する
標準入力からログを取り込み、CloudWatch Logsにアップロードするので、他のアプリケーションの出力をこのスクリプトにリダイレクトして使用する

@example
    some command | ./write-logs-to-aws-from-stdin log_group log_stream
    echo 'Some logs' | ./write-logs-to-aws-from-stdin '/aws/some-system' 'sample-stream'
"""

import watchtower
import logging
import sys

log_group = sys.argv[1]
stream_name = sys.argv[2]

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('aws-cloud-watch-logs')
logger.addHandler(
    watchtower.CloudWatchLogHandler(
        log_group=log_group,
        stream_name=stream_name
    )
)

if __name__ == '__main__':
    while True:
        logger.debug(input())
